import type { Announcement, AttendanceRecord, AttendanceSession, Course, UserProfile } from '../types'

export const mockCourses: Course[] = [
  { id: 'c1', name: 'Microeconomics II', code: 'ECO201', category: 'DSC_MAIN_6', maxAttendanceMarks: 6, teacherId: 'teacher_demo_1' },
  { id: 'c2', name: 'Statistics for Economics', code: 'ECO202', category: 'DSC_MAIN_5', maxAttendanceMarks: 5, teacherId: 'teacher_demo_1' },
  { id: 'c3', name: 'Environmental Studies', code: 'GE101', category: 'GE_5', maxAttendanceMarks: 5, teacherId: 'teacher_demo_2' },
  { id: 'c4', name: 'Data Skills Lab', code: 'SEC101', category: 'SEC_2', maxAttendanceMarks: 2, teacherId: 'teacher_demo_2' },
]

export const mockUsers: (UserProfile & { id: string })[] = [
  {
    id: 'student_demo_1',
    uid: 'student_demo_1',
    name: 'Aarav Sharma',
    email: 'student@college.edu',
    role: 'student',
    rollNumber: '2024-ECO-042',
    course: 'B.A. (Hons) Economics',
    mobileNumber: '+91 98765 43210',
    emailNotificationsEnabled: true,
    enrolledCourseIds: ['c1', 'c2', 'c3', 'c4'],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
  },
  {
    id: 'teacher_demo_1',
    uid: 'teacher_demo_1',
    name: 'Dr. Ramesh Gupta',
    email: 'teacher@college.edu',
    role: 'teacher',
    mobileNumber: '+91 98123 45678',
    assignedCourseIds: ['c1', 'c2'],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 60,
  },
  {
    id: 'cr_demo_1',
    uid: 'cr_demo_1',
    name: 'Priya Verma (CR)',
    email: 'cr@college.edu',
    role: 'cr',
    rollNumber: '2024-ECO-001',
    course: 'B.A. (Hons) Economics',
    assignedClass: 'B.A. (Hons) Economics - Sem IV',
    mobileNumber: '+91 97654 32109',
    enrolledCourseIds: ['c1', 'c2', 'c3', 'c4'],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
  },
  {
    id: 'student_demo_2',
    uid: 'student_demo_2',
    name: 'Ananya Iyer',
    email: 'ananya@college.edu',
    role: 'student',
    rollNumber: '2024-ECO-015',
    course: 'B.A. (Hons) Economics',
    mobileNumber: '+91 98234 56789',
    emailNotificationsEnabled: true,
    enrolledCourseIds: ['c1', 'c2', 'c3'],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
  },
  {
    id: 'student_demo_3',
    uid: 'student_demo_3',
    name: 'Rohan Mehta',
    email: 'rohan@college.edu',
    role: 'student',
    rollNumber: '2024-ECO-028',
    course: 'B.A. (Hons) Economics',
    mobileNumber: '+91 98345 67890',
    emailNotificationsEnabled: false,
    enrolledCourseIds: ['c1', 'c2', 'c4'],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
  },
  {
    id: 'student_demo_4',
    uid: 'student_demo_4',
    name: 'Sneha Kapoor',
    email: 'sneha@college.edu',
    role: 'student',
    rollNumber: '2024-ECO-033',
    course: 'B.A. (Hons) Economics',
    mobileNumber: '+91 98456 78901',
    emailNotificationsEnabled: true,
    enrolledCourseIds: ['c1', 'c2', 'c3', 'c4'],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
  },
]

export const mockAnnouncements: Announcement[] = [
  {
    id: 'a1',
    title: 'Mid-sem exam schedule released',
    message: 'Check the notice board for hall tickets and timing.',
    category: 'Exam',
    isUrgent: true,
    authorId: 'cr_demo_1',
    authorName: 'Priya Verma (CR)',
    createdAt: Date.now() - 1000 * 60 * 60 * 2,
    isActive: true,
  },
  {
    id: 'a2',
    title: 'Guest lecture on Behavioral Economics',
    message: 'Friday 2 PM in the College Auditorium. Attendance is mandatory for Semester IV.',
    category: 'Academic',
    isUrgent: false,
    authorId: 'cr_demo_1',
    authorName: 'Priya Verma (CR)',
    createdAt: Date.now() - 1000 * 60 * 60 * 8,
    isActive: true,
  },
  {
    id: 'a3',
    title: 'Campus Green Drive this Saturday',
    message: 'Join the Environmental Club at North Gate at 9 AM for tree plantation.',
    category: 'Event',
    isUrgent: false,
    authorId: 'cr_demo_1',
    authorName: 'Priya Verma (CR)',
    createdAt: Date.now() - 1000 * 60 * 60 * 24,
    isActive: true,
  },
]

export const mockAttendanceSessions: AttendanceSession[] = [
  {
    id: 'sess_1',
    teacherId: 'teacher_demo_1',
    courseId: 'c1',
    courseName: 'Microeconomics II',
    date: '2026-09-01',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
    totalStudents: 5,
    presentCount: 4,
    absentCount: 1,
  },
  {
    id: 'sess_2',
    teacherId: 'teacher_demo_1',
    courseId: 'c1',
    courseName: 'Microeconomics II',
    date: '2026-09-03',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
    totalStudents: 5,
    presentCount: 5,
    absentCount: 0,
  },
  {
    id: 'sess_3',
    teacherId: 'teacher_demo_1',
    courseId: 'c2',
    courseName: 'Statistics for Economics',
    date: '2026-09-02',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    totalStudents: 5,
    presentCount: 4,
    absentCount: 1,
  },
]

export const mockAttendanceRecords: AttendanceRecord[] = [
  // Session 1 (2026-09-01, c1)
  {
    id: 'rec_c1_s1_1',
    studentId: 'student_demo_1',
    studentName: 'Aarav Sharma',
    rollNumber: '2024-ECO-042',
    courseId: 'c1',
    courseName: 'Microeconomics II',
    date: '2026-09-01',
    time: '09:05 AM',
    status: 'present',
    source: 'teacher_marked',
    locationStatus: 'unavailable',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
  },
  {
    id: 'rec_c1_s1_2',
    studentId: 'student_demo_2',
    studentName: 'Ananya Iyer',
    rollNumber: '2024-ECO-015',
    courseId: 'c1',
    courseName: 'Microeconomics II',
    date: '2026-09-01',
    time: '09:05 AM',
    status: 'present',
    source: 'teacher_marked',
    locationStatus: 'unavailable',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
  },
  {
    id: 'rec_c1_s1_3',
    studentId: 'student_demo_3',
    studentName: 'Rohan Mehta',
    rollNumber: '2024-ECO-028',
    courseId: 'c1',
    courseName: 'Microeconomics II',
    date: '2026-09-01',
    time: '09:05 AM',
    status: 'absent',
    source: 'teacher_marked',
    locationStatus: 'unavailable',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
  },
  {
    id: 'rec_c1_s1_4',
    studentId: 'student_demo_4',
    studentName: 'Sneha Kapoor',
    rollNumber: '2024-ECO-033',
    courseId: 'c1',
    courseName: 'Microeconomics II',
    date: '2026-09-01',
    time: '09:05 AM',
    status: 'present',
    source: 'teacher_marked',
    locationStatus: 'unavailable',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
  },
  {
    id: 'rec_c1_s1_5',
    studentId: 'cr_demo_1',
    studentName: 'Priya Verma (CR)',
    rollNumber: '2024-ECO-001',
    courseId: 'c1',
    courseName: 'Microeconomics II',
    date: '2026-09-01',
    time: '09:05 AM',
    status: 'present',
    source: 'teacher_marked',
    locationStatus: 'unavailable',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
  },

  // Session 2 (2026-09-03, c1)
  {
    id: 'rec_c1_s2_1',
    studentId: 'student_demo_1',
    studentName: 'Aarav Sharma',
    rollNumber: '2024-ECO-042',
    courseId: 'c1',
    courseName: 'Microeconomics II',
    date: '2026-09-03',
    time: '09:00 AM',
    status: 'present',
    source: 'teacher_marked',
    locationStatus: 'unavailable',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },
  {
    id: 'rec_c1_s2_2',
    studentId: 'student_demo_2',
    studentName: 'Ananya Iyer',
    rollNumber: '2024-ECO-015',
    courseId: 'c1',
    courseName: 'Microeconomics II',
    date: '2026-09-03',
    time: '09:00 AM',
    status: 'present',
    source: 'teacher_marked',
    locationStatus: 'unavailable',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },
  {
    id: 'rec_c1_s2_3',
    studentId: 'student_demo_3',
    studentName: 'Rohan Mehta',
    rollNumber: '2024-ECO-028',
    courseId: 'c1',
    courseName: 'Microeconomics II',
    date: '2026-09-03',
    time: '09:00 AM',
    status: 'present',
    source: 'teacher_marked',
    locationStatus: 'unavailable',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },
  {
    id: 'rec_c1_s2_4',
    studentId: 'student_demo_4',
    studentName: 'Sneha Kapoor',
    rollNumber: '2024-ECO-033',
    courseId: 'c1',
    courseName: 'Microeconomics II',
    date: '2026-09-03',
    time: '09:00 AM',
    status: 'present',
    source: 'teacher_marked',
    locationStatus: 'unavailable',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },
  {
    id: 'rec_c1_s2_5',
    studentId: 'cr_demo_1',
    studentName: 'Priya Verma (CR)',
    rollNumber: '2024-ECO-001',
    courseId: 'c1',
    courseName: 'Microeconomics II',
    date: '2026-09-03',
    time: '09:00 AM',
    status: 'present',
    source: 'teacher_marked',
    locationStatus: 'unavailable',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },

  // Student Self Marked (Pending)
  {
    id: 'rec_self_pending_1',
    studentId: 'student_demo_1',
    studentName: 'Aarav Sharma',
    rollNumber: '2024-ECO-042',
    courseId: 'c1',
    courseName: 'Microeconomics II',
    date: new Date().toISOString().slice(0, 10),
    time: '10:15 AM',
    status: 'present',
    source: 'student_self_checkin',
    verificationStatus: 'pending',
    photoUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="320" height="240" viewBox="0 0 320 240"><rect width="320" height="240" fill="%232563eb"/><circle cx="160" cy="100" r="45" fill="white"/><circle cx="160" cy="200" r="70" fill="white"/><text x="160" y="230" text-anchor="middle" fill="%231e293b" font-family="sans-serif" font-size="12" font-weight="bold">Self Attendance Photo</text></svg>',
    photoTimestamp: Date.now() - 1000 * 60 * 45,
    geoTag: { latitude: 28.6892, longitude: 77.209, accuracy: 12 },
    locationStatus: 'captured',
    createdAt: Date.now() - 1000 * 60 * 45,
  },
]
